name: "NFC.cool"
baseURL: "https://new.nfc.cool"
description: "Scan NFC, QR & Barcodes, Documents, 3D Objects and Rooms"
language: "en"

contentDirectory: "Content"
outputDirectory: "_Site"
assetsDirectory: "Content/Assets"
blogURLPrefix: "blog"
redirectsFile: "redirects.yaml"
categories: []

author:
  name: "NFC.cool"
  email: "hello@nfc.cool"

navigation:
  logo:
    text: "NFC.cool"
  items:
    - title: "NFC"
      url: "/nfc-reader-writer/"
    - title: "QR & Barcode"
      url: "/qr-barcode-scanner/"
    - title: "Documents"
      url: "/document-scanner/"
    - title: "3D Scanner"
      url: "/3d-room-scanner/"
    - title: "Business Card"
      url: "/business-card/"
    - title: "Blog"
      url: "https://blog.nfc.cool"
    - title: "Support"
      url: "/contact/"
  showSearch: false
  showThemeToggle: true

homePage:
  title: "NFC.cool"
  subtitle: "The All-in-One Scanner for Your Smartphone"

sections: []

footer:
  copyrightName: "NFC.cool"
  startYear: 2024
  social:
    - platform: "instagram"
      url: "https://www.instagram.com/nfc.cool"
    - platform: "twitter"
      url: "https://twitter.com/NFC_for_iPhone"
    - platform: "youtube"
      url: "https://www.youtube.com/@NFC_cool"
    - platform: "tiktok"
      url: "https://www.tiktok.com/@nfc.cool"
    - platform: "facebook"
      url: "https://www.facebook.com/NFC.cool/"
  links:
    - title: "Business Card"
      url: "/business-card/"
    - title: "Privacy"
      url: "/privacy-policy/"
    - title: "Terms"
      url: "/terms/"